Lis histogram element
legumeinfo/web-components pull request #386
Opened 2024-05-01 16:26 UTC by ctcncgr

Adds a component to use for histograms.

See:

http://dev.lis.ncgr.org:50050/dev/core/lis-histogram-element.html

Docs:

http://dev.lis.ncgr.org:50050/docs/classes/core_components.LisHistogramElement.html

2024-05-01 16:32 UTC, ctcncgr commented
No rush @adf-ncgr and @alancleary as you guys have time to review this. I'm going to move on to other views in the meantime. DSCensor replace inc...

2024-05-07 21:22 UTC, alancleary requested changes
Overall I think this is a solid start. There's a handful of minor changes that need to be made; see my code comments for details.

Two things I want to discuss here are:

1. The size of the component is completely independent of the component's container so I don't see the need for the ResizeObserver. I think it would be cool if the width/height of the histogram were drawn to be the width/height of the container if a width/weight isn't explicitly specified. For example, you would give an explicit width but leave the height empty so the height would be the size of the container. Alternatively, it might make sense to let the "name" axis to be as large as it needs to be to fit the given data.
2. I think having `xlabel` and `ylabel` properties is confusing because the orientation switches what axis the labels are in. Would it make sense instead to name the label by the data on their axis? For example, `nameLabel` and `countLabel`.

2024-05-07 21:22 UTC, alancleary commented on src/core/lis-histogram-element.ts
> +    svgContainer
The edge of the yAxis label is being trimmed in the example. Can this be adjusted or the space allocated dynamically?

2024-05-13 16:22 UTC, ctcncgr commented on src/core/lis-histogram-element.ts
> +  protected resizeObserverController = new LisResizeObserverController(
I had originally tested out putting the svg in a sizable div, but it ended up being buggy. I forgot to remove this. When I add it back I'll put this back in.

2024-05-14 17:59 UTC, ctcncgr commented on dev/core/lis-histogram-element.html
> +  <div class="uk-container" style="overflow: visible;">
This is a mistake that was leftover. It's not actually in the example code anymore on the example site. Will Fix.

2024-06-19 17:51 UTC, ctcncgr commented
Closing this. Will resubmit with changes so its easier to track.

2024-06-19 17:51 UTC, closed without merging