Update to go with new graphql-server based on mine 5.1.0.2
legumeinfo/web-components pull request #41
Opened 2023-01-26 15:28 UTC by sammyjava

This is the update that I implemented to go with the mine-based graphql-server. The main thing I did was to replace keyword searches (which can be unreliable and insufficient) with path query searches in graphql-server, which required some minor tweaks here, plus the addition of a couple new components: `lis-publication-search-element`, `lis-qtl-search-element`, along with updates to `lis-gene-search-element` and `lis-trait-search-element`.

(Note that jekyll-legumeinfo will only contain `lis-gene-search-element` and `lis-publication-search-element` if it queries against LegumeMine since LegumeMine does not contain genetic data.)

2023-01-26 22:35 UTC, alancleary commented on create-web-component.md
> +You may now copy `web-components.bundled.js` to a web site where you want to implement your new web component.
This is an excellent tutorial. Thanks for writing it!

2023-01-26 22:41 UTC, alancleary requested changes
Every thing here looks good. Please push a commit that adds the publication search and qtl search elements to the documentation. See [Static Site](https://github.com/legumeinfo/web-components#static-site) in the readme for details.

2023-01-27 15:57 UTC, sammyjava commented
> Every thing here looks good. Please push a commit that adds the publication search and qtl search elements to the documentation. See [Static Site](https://github.com/legumeinfo/web-components#static-site) in the readme for details.

Done. That is so cool.

2023-02-02 17:31 UTC, alancleary approved these changes
All changes have been reviewed and tested. Approved!

2023-02-02 17:31 UTC, merged